### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Genius398** [somePythonProgrammer/JARVIS#6]

**Comment by somePythonProgrammer** [comment]
You just have to run the code, and say 'computer' for old versions, like when there was 'pion' written on the readme, and 'jarvis' for the coming versions. After saying the wake word, speak a command, and it will reply, or do your stuff.
( 🐛 There are a lot of bugs!)

**Comment by Genius398** [comment]
Where run it

**Comment by somePythonProgrammer** [comment]
In Python.

**Comment by Genius398** [comment]
A bit

**Comment by Genius398** [comment]
I started like 3 days ago

**Comment by Genius398** [comment]
I use spyder

**Comment by somePythonProgrammer** [comment]
Oh. You might have trouble installing packages needed for this repo to run on your machine.

> I use spyder

Also, I recommend using Microsoft Visual Studio code: It is much easier to use for beginners! [REFERENCE](https://code.visualstudio.com/docs/python/python-tutorial)

**Comment by e-coders** [comment]
But, Which Packages are needed? The Error is "No module named "speech_recongition"" means this module doesn't exists. I used "pip install speech_recongition" but It is not found. How??

**Comment by somePythonProgrammer** [comment]
> But, Which Packages are needed? The Error is "No module named "speech_recongition"" means this module doesn't exists. I used "pip install speech_recongition" but It is not found. How??

That's the mistake many people make. THE PACKAGE NAME DOES NOT HAVE TO MATCH THE IMPORT NAME!

An example:

We do: pip install opencv-python
And for the import we do: import cv2

## How to fix the issue

Run this command:
python -m pip uninstall speech_recognition && python -m pip install SpeechRecongition

**Comment by e-coders** [comment]
thanks!

**Comment by somePythonProgrammer** [comment]
Any time.

**Comment by e-coders** [comment]
THe Spyder Application is used for pure python development, but We ONLY needs to edit our python files, and colorful formatting and easily running & Packages. so the best IDE is Visual Studio contains more!!

**Comment by e-coders** [comment]
THe Spyder Application is used for pure python development, but We ONLY needs to edit our python files, and colorful formatting and easily running & Packages. so the best IDE is Visual Studio contains more!!

**Comment by e-coders** [comment]
ummm
```
D:\JARVIS\JARVIS-0.0.2>app.py
Traceback (most recent call last):
  File "D:\JARVIS\JARVIS-0.0.2\app.py", line 2, in <module>
    from __init__ import *
  File "D:\JARVIS\JARVIS-0.0.2\__init__.py", line 2, in <module>
    from bot.chatbot import *
  File "D:\JARVIS\JARVIS-0.0.2\bot\chatbot.py", line 2, in <module>
    from chatterbot import ChatBot
ModuleNotFoundError: No module named 'chatterbot'
```

**Comment by somePythonProgrammer** [comment]
@e-coders In the new release, run DepInstaller.py to automatically install all dependencies and then run JARVIS.
Run this code in the repository directory:

    python DepInstaller.py && python __main__.py

**Comment by e-coders** [comment]
WOW!!!!

**Comment by somePythonProgrammer** [comment]
> Also, after I make another release, It will be possible to run JARVIS on windows machines WITHOUT python, as we will be adding an installer!

Done!

**Comment by somePythonProgrammer** [comment]
The installer is is the new release!
